import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-property-management-vendor-sla-invoice-audit",
  "engine": "recovery",
  "title": "Property Management Vendor SLA & Invoice Audit",
  "shortTitle": "Property Management Vendor SLA and Invoice Audit",
  "tagline": "Quantify, recover, and prevent financial leakage through property management vendor sla & invoice audit",
  "industry": "Property Vendor Spend Recovery",
  "uiPort": 4616,
  "apiPort": 5616,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Property Management Vendor SLA & Invoice Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect vendor contracts, properties, assets, work orders, technician events, preventive maintenance, labor, materials, trips, emergencies, SLAs, invoices, and credits in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "billedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Vendor Billed Amount",
    "expectedLabel": "Work-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Property Management Vendor SLA & Invoice Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("vendor-contract-library","PMV01","Vendor contract library","Execute vendor contract library using vendor contracts, properties, assets, work orders, technician events, preventive maintenance, labor, materials, trips, emergencies, SLAs, invoices, and credits.","Produce a governed vendor contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Property","text","Vendor / Property · Standard Case"],["caseReference","Vendor contract library Reference","text","PMV01-2026-001"],["billedAmount","Vendor Billed Amount","currency",882500],["supportedAmount","Work-Supported Amount","currency",758950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Vendor contract library case","Property asset registry case","Work-order ingestion case","Arrival completion tracking case","Preventive maintenance validation case"]}),
feature("property-asset-registry","PMV02","Property asset registry","Execute property asset registry using vendor contracts, properties, assets, work orders, technician events, preventive maintenance, labor, materials, trips, emergencies, SLAs, invoices, and credits.","Produce a governed property asset registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Property","text","Vendor / Property · Standard Case"],["caseReference","Property asset registry Reference","text","PMV02-2026-001"],["billedAmount","Vendor Billed Amount","currency",882500],["supportedAmount","Work-Supported Amount","currency",758950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Vendor contract library case","Property asset registry case","Work-order ingestion case","Arrival completion tracking case","Preventive maintenance validation case"]}),
feature("work-order-ingestion","PMV03","Work-order ingestion","Execute work-order ingestion using vendor contracts, properties, assets, work orders, technician events, preventive maintenance, labor, materials, trips, emergencies, SLAs, invoices, and credits.","Produce a governed work-order ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Property","text","Vendor / Property · Standard Case"],["caseReference","Work-order ingestion Reference","text","PMV03-2026-001"],["billedAmount","Vendor Billed Amount","currency",882500],["supportedAmount","Work-Supported Amount","currency",758950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Vendor contract library case","Property asset registry case","Work-order ingestion case","Arrival completion tracking case","Preventive maintenance validation case"]}),
feature("arrival-completion-tracking","PMV04","Arrival completion tracking","Execute arrival completion tracking using vendor contracts, properties, assets, work orders, technician events, preventive maintenance, labor, materials, trips, emergencies, SLAs, invoices, and credits.","Produce a governed arrival completion tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Property","text","Vendor / Property · Standard Case"],["caseReference","Arrival completion tracking Reference","text","PMV04-2026-001"],["billedAmount","Vendor Billed Amount","currency",882500],["supportedAmount","Work-Supported Amount","currency",758950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Vendor contract library case","Property asset registry case","Work-order ingestion case","Arrival completion tracking case","Preventive maintenance validation case"]}),
feature("preventive-maintenance-validation","PMV05","Preventive maintenance validation","Execute preventive maintenance validation using vendor contracts, properties, assets, work orders, technician events, preventive maintenance, labor, materials, trips, emergencies, SLAs, invoices, and credits.","Produce a governed preventive maintenance validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Property","text","Vendor / Property · Standard Case"],["caseReference","Preventive maintenance validation Reference","text","PMV05-2026-001"],["billedAmount","Vendor Billed Amount","currency",882500],["supportedAmount","Work-Supported Amount","currency",758950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Vendor contract library case","Property asset registry case","Work-order ingestion case","Arrival completion tracking case","Preventive maintenance validation case"]}),
feature("labor-rate-audit","PMV06","Labor rate audit","Execute labor rate audit using vendor contracts, properties, assets, work orders, technician events, preventive maintenance, labor, materials, trips, emergencies, SLAs, invoices, and credits.","Produce a governed labor rate audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Property","text","Vendor / Property · Standard Case"],["caseReference","Labor rate audit Reference","text","PMV06-2026-001"],["billedAmount","Vendor Billed Amount","currency",882500],["supportedAmount","Work-Supported Amount","currency",758950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Vendor contract library case","Property asset registry case","Work-order ingestion case","Arrival completion tracking case","Preventive maintenance validation case"]}),
feature("material-rate-audit","PMV07","Material rate audit","Execute material rate audit using vendor contracts, properties, assets, work orders, technician events, preventive maintenance, labor, materials, trips, emergencies, SLAs, invoices, and credits.","Produce a governed material rate audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Property","text","Vendor / Property · Standard Case"],["caseReference","Material rate audit Reference","text","PMV07-2026-001"],["billedAmount","Vendor Billed Amount","currency",882500],["supportedAmount","Work-Supported Amount","currency",758950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Vendor contract library case","Property asset registry case","Work-order ingestion case","Arrival completion tracking case","Preventive maintenance validation case"]}),
feature("trip-emergency-fee-validation","PMV08","Trip emergency fee validation","Execute trip emergency fee validation using vendor contracts, properties, assets, work orders, technician events, preventive maintenance, labor, materials, trips, emergencies, SLAs, invoices, and credits.","Produce a governed trip emergency fee validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Property","text","Vendor / Property · Standard Case"],["caseReference","Trip emergency fee validation Reference","text","PMV08-2026-001"],["billedAmount","Vendor Billed Amount","currency",882500],["supportedAmount","Work-Supported Amount","currency",758950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Vendor contract library case","Property asset registry case","Work-order ingestion case","Arrival completion tracking case","Preventive maintenance validation case"]}),
feature("duplicate-work-order-billing","PMV09","Duplicate work-order billing","Execute duplicate work-order billing using vendor contracts, properties, assets, work orders, technician events, preventive maintenance, labor, materials, trips, emergencies, SLAs, invoices, and credits.","Produce a governed duplicate work-order billing decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Property","text","Vendor / Property · Standard Case"],["caseReference","Duplicate work-order billing Reference","text","PMV09-2026-001"],["billedAmount","Vendor Billed Amount","currency",882500],["supportedAmount","Work-Supported Amount","currency",758950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Vendor contract library case","Property asset registry case","Work-order ingestion case","Arrival completion tracking case","Preventive maintenance validation case"]}),
feature("sla-response-monitoring","PMV10","SLA response monitoring","Execute sla response monitoring using vendor contracts, properties, assets, work orders, technician events, preventive maintenance, labor, materials, trips, emergencies, SLAs, invoices, and credits.","Produce a governed sla response monitoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Property","text","Vendor / Property · Standard Case"],["caseReference","SLA response monitoring Reference","text","PMV10-2026-001"],["billedAmount","Vendor Billed Amount","currency",882500],["supportedAmount","Work-Supported Amount","currency",758950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Vendor contract library case","Property asset registry case","Work-order ingestion case","Arrival completion tracking case","Preventive maintenance validation case"]}),
feature("service-credit-calculation","PMV11","Service credit calculation","Execute service credit calculation using vendor contracts, properties, assets, work orders, technician events, preventive maintenance, labor, materials, trips, emergencies, SLAs, invoices, and credits.","Produce a governed service credit calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Property","text","Vendor / Property · Standard Case"],["caseReference","Service credit calculation Reference","text","PMV11-2026-001"],["billedAmount","Vendor Billed Amount","currency",882500],["supportedAmount","Work-Supported Amount","currency",758950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Vendor contract library case","Property asset registry case","Work-order ingestion case","Arrival completion tracking case","Preventive maintenance validation case"]}),
feature("invoice-matching","PMV12","Invoice matching","Execute invoice matching using vendor contracts, properties, assets, work orders, technician events, preventive maintenance, labor, materials, trips, emergencies, SLAs, invoices, and credits.","Produce a governed invoice matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Property","text","Vendor / Property · Standard Case"],["caseReference","Invoice matching Reference","text","PMV12-2026-001"],["billedAmount","Vendor Billed Amount","currency",882500],["supportedAmount","Work-Supported Amount","currency",758950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Vendor contract library case","Property asset registry case","Work-order ingestion case","Arrival completion tracking case","Preventive maintenance validation case"]}),
feature("manager-approval","PMV13","Manager approval","Execute manager approval using vendor contracts, properties, assets, work orders, technician events, preventive maintenance, labor, materials, trips, emergencies, SLAs, invoices, and credits.","Produce a governed manager approval decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Property","text","Vendor / Property · Standard Case"],["caseReference","Manager approval Reference","text","PMV13-2026-001"],["billedAmount","Vendor Billed Amount","currency",882500],["supportedAmount","Work-Supported Amount","currency",758950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Vendor contract library case","Property asset registry case","Work-order ingestion case","Arrival completion tracking case","Preventive maintenance validation case"]}),
feature("vendor-dispute-workflow","PMV14","Vendor dispute workflow","Execute vendor dispute workflow using vendor contracts, properties, assets, work orders, technician events, preventive maintenance, labor, materials, trips, emergencies, SLAs, invoices, and credits.","Produce a governed vendor dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Property","text","Vendor / Property · Standard Case"],["caseReference","Vendor dispute workflow Reference","text","PMV14-2026-001"],["billedAmount","Vendor Billed Amount","currency",882500],["supportedAmount","Work-Supported Amount","currency",758950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Vendor contract library case","Property asset registry case","Work-order ingestion case","Arrival completion tracking case","Preventive maintenance validation case"]}),
feature("property-vendor-analytics","PMV15","Property vendor analytics","Execute property vendor analytics using vendor contracts, properties, assets, work orders, technician events, preventive maintenance, labor, materials, trips, emergencies, SLAs, invoices, and credits.","Produce a governed property vendor analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Property","text","Vendor / Property · Standard Case"],["caseReference","Property vendor analytics Reference","text","PMV15-2026-001"],["billedAmount","Vendor Billed Amount","currency",882500],["supportedAmount","Work-Supported Amount","currency",758950],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Vendor contract library case","Property asset registry case","Work-order ingestion case","Arrival completion tracking case","Preventive maintenance validation case"]})
]);
